# Site settings
title: Journal
header-img: img/post-bg-04.jpg
email: hello@duskr.co
description: "This is mostly about writing things."
baseurl: ""
url: "http://duskr.github.io/"
twitter_username: jonathanlurie
github_username:  jonathanlurie
facebook_username:  jonathan.lurie

# octopress options
post_ext: md
page_ext: html
post_layout: post
page_layout: page

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
